NODE_ENV=testing \
SILENT_START=true \
APPLICATION_SERVER="$APP_STORE_APPLICATION_SERVER" \
APPLICATION_SERVER_TOKEN="$APP_STORE_APPLICATION_SERVER_TOKEN" \
DASHBOARD_SERVER="$APP_STORE_DASHBOARD_SERVER" \
DOMAIN="$APP_STORE_DOMAIN" \
STRIPE_KEY="$APP_STORE_STRIPE_KEY" \
STRIPE_PUBLISHABLE_KEY="$APP_STORE_STRIPE_PUBLISHABLE_KEY" \
SUBSCRIPTIONS_ENDPOINT_SECRET1="$APP_STORE_SUBSCRIPTIONS_ENDPOINT_SECRET1" \
SUBSCRIPTIONS_ENDPOINT_SECRET2="$APP_STORE_SUBSCRIPTIONS_ENDPOINT_SECRET2" \
CONNECT_ENDPOINT_SECRET="$APP_STORE_CONNECT_ENDPOINT_SECRET" \
STRIPE_JS="false" \
IP="0.0.0.0" \
PORT=$APP_STORE_DASHBOARD_SERVER_PORT \
PAGE_SIZE=40 \
STORAGE_PATH="~/tmp/data1" \
mocha src/www --recursive --timeout 480000 --slow 4800000