NODE_ENV=testing \
SILENT_START=true \
DASHBOARD_SERVER="$USERAPPSTORE_DASHBOARD_SERVER" \
PORT=8200 \
DOMAIN="$USERAPPSTORE_DOMAIN" \
STRIPE_KEY="$USERAPPSTORE_STRIPE_KEY" \
STRIPE_PUBLISHABLE_KEY="$USERAPPSTORE_STRIPE_PUBLISHABLE_KEY" \
CONNECT_ENDPOINT_SECRET="$USERAPPSTORE_CONNECT_ENDPOINT_SECRET" \
SUBSCRIPTIONS_ENDPOINT_SECRET="$USERAPPSTORE_SUBSCRIPTIONS_ENDPOINT_SECRET" \
STRIPE_JS="false" \
IP="0.0.0.0" \
DATA="/tmp/data" \
mocha node_modules/@userappstore --recursive --timeout 240000 slow 240000